class ErrorCode:
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    DUPLICATE_EMPLOYEE = "DUPLICATE_EMPLOYEE"
    DUPLICATE_ATTENDANCE = "DUPLICATE_ATTENDANCE"
    DATABASE_ERROR = "DATABASE_ERROR"
    SERVER_ERROR = "SERVER_ERROR"
